routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::group(['middleware' => ['web']], function(){
    Route::get('blog/{slug}',['as' => 'blog.single', 'uses' => 'BlogController@getSingle'])->where('slug', '[\w\d\-\_]+');
    Route::get('blog',['as' => 'blog.index', 'uses' => 'BlogController@getIndex']);
    Route::get('/', 'PagesController@getIndex');
    Route::get('about', 'PagesController@getAbout');
    Route::get('contacts', 'PagesController@getContacts');
//    Route::get('password/reset/{token?}', 'Auth\PasswordController@showResetForm');
//    Route::post('password/email');
});
Route::group(['middleware' => ['auth']], function(){
    Route::resource('posts', 'PostController');
    Route::resource('admin/pages', 'MakePagesController');
    Route::post('posts/upload', 'PostController@imageUploadPost')->name('image.upload.post');
    Route::get('admin', [
        'as' => 'admin.index',
        'uses' => 'adminController@getIndex'
    ]);
});
Auth::routes();

Route::get('/home', 'HomeController@index')->name('index');

resources/views/partials/_content.blade.php
@yield('content')

resources/views/partials/_footer.blade.php
<div class="footer">
    <hr />
    <p class="text-center">Copyright gnexus - All Rights Reserved</p>
</div>
<script src="{{ mix('js/app.js') }}"></script>

resources/views/partials/_head.blade.php
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Laravel Blog @yield('title')</title>

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="{{ mix('css/app.css') }}">
</head>

resources/views/partials/_messages.blade.php
@if(Session::has('success'))
    <div class="alert alert-success" role="alert">
        <strong>Success: </strong>{{ Session::get('success') }}
    </div>
@endif

@if(count($errors) > 0)
    <div class="alert alert-danger" role="alert">
        <strong>Errors: </strong>
        <ul>
            @foreach($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

@if(Session::has('danger'))
    <div class="alert alert-danger" role="alert">
        <strong>Success: </strong>{{ Session::get('danger') }}
    </div>
@endif

resources/views/partials/_nav.blade.php
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">Laravel</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item {{ Request::is('/') ? 'active' : ''}}">
                <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item {{ Request::is('blog') ? 'active' : ''}}">
                <a class="nav-link" href="/blog">Blog</a>
            </li>
            <li class="nav-item {{ Request::is('about') ? 'active' : ''}}">
                <a class="nav-link" href="/about">About</a>
            </li>
            <li class="nav-item {{ Request::is('contacts') ? 'active' : ''}}">
                <a class="nav-link" href="/contacts">Contacts</a>
            </li>
        </ul>
        <div class="btn-group">

            {{--<ul class="btn nav navbar dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">--}}
                {{--My account--}}
            {{--</ul>--}}
            {{--<div class="dropdown-menu dropdown-menu-right">--}}
                {{--<a class="dropdown-item" href="{{ route('posts.index') }}">Posts</a>--}}
                {{--<a class="dropdown-item" href="#">Another action</a>--}}
                {{--<a class="dropdown-item" href="#">Logout</a>--}}

            {{--</div>--}}
            @guest
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item {{ Request::is('contacts') ? 'active' : ''}}">
                        <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                    </li>
                </ul>
                @if (Route::has('register'))
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item {{ Request::is('contacts') ? 'active' : ''}}">
                            <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                        </li>
                    </ul>
                @endif
            @else
                <ul class="btn nav navbar dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {{ Auth::user()->name }}
                </ul>
                <div class="dropdown-menu dropdown-menu-right">
                    <a class="dropdown-item" href="{{ route('admin.index') }}">Admin</a>
                    <a class="dropdown-item" href="{{ route('posts.index') }}">Posts</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <a class="dropdown-item" href="{{ route('logout') }}"
                       onclick="event.preventDefault();
                        document.getElementById('logout-form').submit();">
                        {{ __('Logout') }}
                    </a>
                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        @csrf
                    </form>
                </div>
            @endguest
        </div>
    </div>
</nav>

resources/views/partials/_upload-image.blade.php
<form action="{{ route('image.upload.post') }}" method="POST" enctype="multipart/form-data">
    @csrf
    <div class="row">
        <div class="col-md-6">
            <input type="file" name="image" id="file_input">
        </div>
        <div class="col-md-6">
            <button type="submit" class="btn btn-success" id="loadImg">Загрузить</button>
        </div>
    </div>
</form>