routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::group(['middleware' => ['web']], function(){
    Route::get('blog/{slug}',['as' => 'blog.single', 'uses' => 'BlogController@getSingle'])->where('slug', '[\w\d\-\_]+');
    Route::get('blog',['as' => 'blog.index', 'uses' => 'BlogController@getIndex']);
    Route::get('/', 'PagesController@getIndex');
    Route::get('about', 'PagesController@getAbout');
    Route::get('contacts', 'PagesController@getContacts');
//    Route::get('password/reset/{token?}', 'Auth\PasswordController@showResetForm');
//    Route::post('password/email');
});
Route::group(['middleware' => ['auth']], function(){
    Route::resource('posts', 'PostController');
    Route::resource('admin/pages', 'MakePagesController');
    Route::post('posts/upload', 'PostController@imageUploadPost')->name('image.upload.post');
    Route::get('admin', [
        'as' => 'admin.index',
        'uses' => 'adminController@getIndex'
    ]);
});
Auth::routes();

Route::get('/home', 'HomeController@index')->name('index');

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    public static function getPosts()
    {
        $thisobj = new self();
        return $thisobj->orderBy('created_at', 'desc')->limit(4)->get();
    }

    public function category()
    {
        return $this->belongsTo('App\Category');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Post;
use Illuminate\Http\Request;
use Session;
use Illuminate\Validation\Rule;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::orderBy('id', 'desc')->paginate(5);

        return view('posts.index')->withPosts($posts);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('posts/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, array(
            'title' => 'required|max:255',
            'slug' => 'required|alpha_dash|min:5|max:255|unique:posts,slug',
            'image' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            'body' => 'required'
        ));


        $file = $request->file('image');
        $file_name = time() . $file->getClientOriginalName();
        $file_path = 'images';
        $file->move($file_path, $file_name);

        $post = new Post;

        $post->title = $request->input('title');
        $post->slug = $request->input('slug');
        $post->body = $request->input('body');
        $post->image = $file_name;

        $post->save();

        Session::flash('success','Blog post was successfuly saved! ');

        return redirect()->route('posts.show', $post->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $post = Post::find($id);
        return view('posts.show')->withPost($post);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = Post::find($id);

        return view('posts.edit')->withPost($post);
    }
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // Validate the data
        $this->validate($request, array(
            'title' => 'required|max:255',
            'slug' => ['required','alpha_dash','min:5','max:255', Rule::unique('posts')->ignore($id)],
            'body' => 'required'
        ));
        $post = Post::find($id);

        $post->title = $request->title;
        $post->slug = $request->slug;
        $post->body = $request->body;

        $post->update();

        Session::flash('success','Blog post was successfuly saved! '.$id);

        return redirect()->route('posts.show', $post->id);

        // Save the data to db
        // Set data with success message
        // Redirect with flash data to posts.show
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post = Post::find($id);
        Session::flash('danger','Blog post was deleted');
        $post->delete();
        return redirect()->route('posts.index');

    }
}

resources/views/posts/create.blade.php
@extends('main')
@section('title','Create post')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <h1>Create new post</h1>
                <hr />
                {!! Form::open(['route' => 'posts.store', 'enctype' => 'multipart/form-data']) !!}
                    {{ Form::label('title', 'Title:') }}
                    {{ Form::text('title', null, array('class' => 'form-control'))  }}
                    <br />
                    {{ Form::label('image', 'Image:') }}
                    <br />
                    {{ Form::file('image', null, array('class' => 'form-control'))  }}
                    <br />
                    {{ Form::label('slug', 'Slug:') }}
                    {{ Form::text('slug', null, array('class' => 'form-control'))  }}
                    {{ Form::label('body', 'Post Body:') }}
                    {{ Form::textarea('body', null, array('class' => 'form-control')) }}
                    {{ Form::submit('Create Post', array('class' => 'btn btn-success btn-lg btn-block', 'style' => 'margin-top: 20px')) }}
                {!! Form::close() !!}
{{--                @include('partials._upload-image')--}}
            </div>
        </div>
    </div>
@endsection

resources/views/posts/edit.blade.php
@extends('main')

@section('title','| Edit Post')

@section('content')
    <div class="container">
        {{ Form::model($post, ['route' => ['posts.update', $post->id], 'method' => 'PUT']) }}
        <div class="row">
            <div class="col-md-8">
                {{ Form::label('title','Title:') }}

                {{ Form::text('title', null, ["class" => "form-control-lg form-control"]) }}

                {{ Form::label('slug','Slug:') }}
                {{ Form::text('slug', null, ['class' => 'form-control']) }}
                {{ Form::label('image','Image:') }}
                {{ Form::file('image', ['class' => "form-control", "value" => "$post->image"]) }}
                <hr />
                {{ Form::label('body','Body:') }}

                {{ Form::textarea('body', null, ["class" => "form-control"]) }}
            </div>
            <div class="col-md-4">
                <div class="card card-body bg-light">
                    <dl class="row">
                        <dt class="col-sm-5">Created at:</dt>
                        <dd class="col-sm-7">{{ date('d \of\ F Y', strtotime($post->updated_at)) }}</dd>
                    </dl>
                    <dl class="row">
                        <dt class="col-sm-5">Last uploaded:</dt>
                        <dd class="col-sm-7">{{ date('d \of\ F Y', strtotime($post->updated_at)) }}</dd>
                    </dl>
                    <hr />
                    <div class="row">
                        <div class="col-sm-6">
                            {{ Form::submit('Save', ['class' => 'btn btn-success btn-block']) }}
                        </div>
                        <div class="col-sm-6">
                            {{ Html::linkRoute('posts.show', 'Cancel', array($post->id), array('class' => 'btn btn-block')) }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {{ Form::close() }}
    </div>
@endsection

resources/views/posts/index.blade.php
@extends('main')
@section('title','| Posts List')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-10">
                <h1>All posts</h1>
            </div>

            <div class="col-md-2">
                <a href="{{ route('posts.create') }}" class="btn btn-block btn-primary btn-h1-margin">Create new Post</a>
            </div>
            <div class="col-md-12">
                <hr />
            </div>
        </div> <!-- end of the row -->

        <div class="row">
            <div class="col-md-12">
                <table class="table">
                    <thead>
                        <th>#id</th>
                        <th>Title</th>
                        <th>Body</th>
                        <th>Created at</th>
                        <th></th>
                    </thead>
                    <tbody>
                        @foreach($posts as $post)

                            <tr>
                                <th>{{ $post->id }}</th>

                                <td>{{ $post->title }}</td>
                                <td>{{ substr($post->body, 0, 50) }} {{ strlen($post->body) > 50 ? '...' : '' }}</td>
                                <td>{{ date('d M Y', strtotime($post->created_at)) }}</td>
                                <td>
                                    <a href="{{ route('posts.show',$post->id) }}" class="btn btn-sm btn-success">View</a>
                                    <a href="{{ route('posts.edit', $post->id) }}" class="btn btn-sm btn-primary">Edit</a>
                                </td>
                            </tr>

                        @endforeach
                    </tbody>
                </table>
                <div class="text-center">
                    {!! $posts->links() !!}
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/posts/show.blade.php
@extends('main')

@section('title',"| $post->title")

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <h1 style="margin-bottom: 0;">{{ $post->title }}</h1>
                <hr />
                <p style="margin-top: 20px;" class="lead">{{ $post->body }}</p>
                <img src="{{asset("images/$post->image")}}" class="rounded float-left" alt="...">

            </div>
            <div class="col-md-4">
                <div class="card card-body bg-light">
                    <dl class="row">
                        <dt class="col-sm-5">URL Slug:</dt>
                        <dd class="col-sm-7"><a href="{{ url('blog/'.$post->slug ) }}">{{ url('blog/'.$post->slug) }}</a></dd>
                    </dl>
                    <dl class="row">
                        <dt class="col-sm-5">Created at:</dt>
                        <dd class="col-sm-7">{{ date('d \of\ F Y', strtotime($post->updated_at)) }}</dd>
                    </dl>
                    <dl class="row">
                        <dt class="col-sm-5">Last uploaded:</dt>
                        <dd class="col-sm-7">{{ date('d \of\ F Y', strtotime($post->updated_at)) }}</dd>
                    </dl>
                    <hr />
                    <div class="row">
                        <div class="col-sm-6">
                            {{ Html::linkRoute('posts.edit', 'Edit', array($post->id), array('class' => 'btn btn-primary btn-block')) }}
                        </div>
                        <div class="col-sm-6">
                            {{ Form::model($post, ['route' => ['posts.destroy', $post->id], 'method' => 'DELETE']) }}
                            {{ Form::submit('Delete', ['class' => 'btn btn-danger btn-block']) }}
                            {{ Form::close() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection